name: Reset-DB
run-name: ${{ github.actor }} is reset database ðŸ”±

on:
  workflow_dispatch:
  repository_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: configure vars
        run: |
          echo "${{ secrets.TRADER_DEPLOY_VARS }}" > ./group_vars/vars.yml

      - name: playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook.yml
          directory: ./
          key: ${{ secrets.TIMHSU_KEY }}
          inventory: ${{ secrets.TRADER_HOSTS }}
          options: |
            --tags reset_db
